### ISSUE TITLE
receiver list empty

### ISSUE THREAD

**Issue by Yugzz** [dryan/geckocast#2]
I always get this error : receiver list empty (line 91)
I search in the code but dont find why i get this...
btw the namespace was strange. i try to change it (without success).

ps : sorry if my english is ugly, and ask me if you dont understand something.

eddit : i resolve this error but now geckocast work for few minute then stop ...

**Comment by Cieper** [comment]
I had the same issue, but managed to fix it by registering my Chromecast in the Google Cast SDK Developer Console, and rebooting the Chromecast.
